//actores_model.dart
//url: https://api.themoviedb.org/3/movie/123/credits?api_key=e5ffc1203b7c1bbf876605bd54e27c20
// Generated by https://quicktype.io

class Cast {
  List<Actor> actores = new List();

  Cast.fromJsonList(List<dynamic> jsonList ){
    
    if(jsonList == null) return;
    jsonList.forEach((item){
      final actor = Actor.fromJsonMap(item);
      actores.add(actor);
    });

  }// fromJsonList

}// class Cast

class Actor {
  int castId;
  String character;
  String creditId;
  int gender;
  int id;
  String name;
  int order;
  String profilePath;

  Actor({
    this.castId,
    this.character,
    this.creditId,
    this.gender,
    this.id,
    this.name,
    this.order,
    this.profilePath,
  });

  /**
  fromJsonMap carga el objeto Actor con los atributos mapeados
  {
    "cast_id": 1,
    "character": "Frodo (voice)",
    "credit_id": "52fe421bc3a36847f80047df",
    "gender": 2,
    "id": 16270,
    "name": "Christopher Guard",
    "order": 0,
    "profile_path": "/7jHduhvSkeCVyPH3LQEeMC3hbvV.jpg"
  },
  */
  Actor.fromJsonMap(Map<String,dynamic> json){
    castId		= json["cast_id"];
    character	= json["character"];
    creditId	= json["credit_id"];
    gender		= json["gender"];
    id		    = json["id"];
    name		  = json["name"];
    order		  = json["order"];
    profilePath	= json["profile_path"];
  }

  String getPhoto(){

    if( profilePath == null)
      return "https://gambit.gg/design/images/no-pic.jpg";
    
    return "https://image.tmdb.org/t/p/w500$profilePath";
    
  }// getPhoto

}// class Actor
